# -*- coding: utf-8 -*-
import re

PATH = r"D:\edlanx-website\js\courses-data.js"

SCOPE_LONG = {
"full-stack-web-development": "Full stack developers build and maintain both the frontend and backend of web applications, from the interface a user clicks through to the servers and databases running behind it. It is one of the highest-demand skill sets across Indian product companies, startups, and IT services firms, because a single full stack hire can own a feature end to end instead of waiting on a separate frontend and backend team. Companies building web products, internal tools, e-commerce platforms, and SaaS applications are constantly hiring for this skill, and it stays relevant as frameworks change because the underlying logic of client-server communication rarely does.",
"web-architecture": "Web Architecture is the entry point into frontend and full stack careers: understanding how a browser renders a page, how layout and responsiveness actually work, and how a simple site talks to a server. Every product and agency needs engineers who can turn a design into a fast, accessible, well-structured website before they ever touch a large-scale application. This course is where most working developers actually started, and it builds the foundation that every later specialization (React, Node, mobile, DevOps) sits on top of.",
"python": "Python is the most widely used language for scripting, automation, backend development, data analysis, and AI, which makes it one of the few languages that stays useful no matter which direction your career takes afterward. It is the default teaching language at most engineering colleges and the default production language at most data and AI teams, so Python fluency is assumed rather than asked about in many interviews. Learning it well opens doors into web development, automation tooling, data science, and machine learning without needing to relearn a new language for each.",
"machine-learning": "Machine learning powers recommendation engines, fraud detection, demand forecasting, and automation across finance, e-commerce, healthcare, and product companies, and it has moved from a specialist research skill to a standard expectation on many data and engineering teams. Companies need people who can take a business problem, frame it as a model, and actually ship it into production, not just train a model in a notebook. This course focuses on that full loop: data preparation, model building, evaluation, and deployment, the parts that separate a portfolio project from a job-ready skill.",
"android-app-development": "Android powers the large majority of smartphones in India, and native app developers stay in steady demand across product companies, startups, and IT services firms building consumer and enterprise apps. Businesses that want a real presence on users' phones, not just a mobile website, need engineers who understand the Android platform, its lifecycle, and its publishing process end to end. This course takes you from writing your first Kotlin screen to shipping a real app to the Play Store, the same path a working Android developer follows.",
"data-science": "Data scientists turn raw business data into decisions, a core function in e-commerce, fintech, healthcare, and analytics consulting, wherever a company has more data than it knows what to do with. The role sits between statistics, programming, and business judgment: you're expected to clean messy data, build models that hold up, and explain the result to people who aren't technical. Because almost every industry now runs on data, this is one of the more portable skill sets, moving from finance to retail to healthcare analytics without starting over.",
"artificial-intelligence": "AI skills apply across search, recommendation, automation, and generative tools, and are increasingly required in both tech and non-tech industries adopting AI features into their products. Companies are no longer just hiring dedicated AI researchers, they're expecting product and software engineers to understand how to integrate AI models into real applications. This course builds that practical layer: enough of the underlying theory to reason about what a model can and can't do, plus hands-on experience applying it, rather than treating AI as a black box.",
"ui-ux": "Every digital product, app, or website needs usable, well-designed interfaces, which makes UI/UX a core hiring need across product companies, agencies, and startups building anything customer-facing. A product with a confusing interface loses users no matter how good the underlying technology is, which is why design has become a seat at the product table rather than a final polish step. This course covers the full design process, from talking to users and mapping their problems through wireframes, prototypes, and a portfolio-ready design system.",
"graphic-design": "Brands, agencies, and marketing teams need visual designers for everything from social content and packaging to full brand identity systems, and that need doesn't shrink as more of a brand's presence moves online. A strong visual designer is expected to understand typography, color, and composition well enough to make a brand instantly recognizable across every format it appears in. This course builds that foundation through real design exercises, not just software tutorials, so you leave with a portfolio, not just familiarity with a toolset.",
"ar-vr": "AR/VR is expanding beyond gaming into training simulations, retail try-on experiences, real estate walkthroughs, and industrial visualization, creating demand for developers who can build immersive experiences rather than just conventional 2D apps. As headset and mobile AR hardware becomes more common, companies in education, retail, and manufacturing are experimenting with immersive tools for training and marketing. This course teaches the fundamentals of 3D space, interaction design, and deployment across Unity and WebXR, the two most commonly used toolchains in the industry.",
"devops": "DevOps engineers keep software delivery fast and reliable, a role every product company and IT services firm running cloud infrastructure needs once their applications grow past a handful of servers. The job is about automating the path from code commit to production: containerizing applications, orchestrating them at scale, provisioning infrastructure as code, and catching problems before users do. It is one of the better-paid entry paths into cloud engineering because it sits at the intersection of software and infrastructure, two skill sets that are individually common but rarely combined well.",
"selenium-testing-java": "Automated QA is essential to shipping reliable software fast, and Selenium remains the industry-standard tool for web test automation across companies of every size. As release cycles get shorter, manual testing alone can't keep up, which is why QA automation engineers who can write and maintain a real test suite are in consistent demand. This course builds that skill directly: writing Java-based Selenium tests, structuring them with the Page Object Model, and running them as part of a CI pipeline, the same setup used on real engineering teams.",
"cyber-security": "With rising cyber threats, every company handling digital data now needs security-aware engineers and analysts, from banks and fintech startups to SaaS companies storing customer information. The role spans a wide surface: network security, ethical hacking, cloud and mobile security, and incident response, because attacks don't stay confined to one layer of a system. This course walks through that full surface area with a hands-on, project-based approach so you understand not just the theory of an attack but how to actually detect, prevent, and respond to one.",
"java": "Java remains the backbone of enterprise software, banking systems, and Android development across India's largest IT employers, and its stability is exactly why it stays in demand even as newer languages trend. Large organizations run mission-critical systems on Java because of its maturity, tooling, and predictability, which means Java developers are hired at scale by IT services firms, banks, and enterprise product companies. This course covers core Java and object-oriented programming through to the collections and exception-handling patterns used in real production code.",
"sap": "SAP runs the core operations of most large enterprises, from finance to supply chain, and certified SAP professionals are consistently in demand at IT services and consulting firms implementing and supporting these systems. Because SAP implementations are complex and long-running, companies need people who understand both the software and the business processes it's built around. This course gives you a working overview of SAP's core modules and how they map to real business processes, the starting point for a specialized SAP consulting career.",
"aws": "Cloud is the default deployment target for modern software, and AWS remains the most widely used cloud platform in Indian IT and product companies, from early-stage startups to large enterprises migrating off on-premise infrastructure. Nearly every software role today, from backend developer to DevOps engineer, is expected to have some working knowledge of cloud services, security, and deployment. This course covers the core AWS services and architecture patterns used to design, secure, and deploy production workloads, the practical skill set behind most cloud job postings.",
"embedded-systems": "Embedded engineers build the firmware behind everything from consumer electronics to automotive and industrial systems, a core hiring need in India's growing electronics manufacturing and product design sector. Unlike application software, embedded code runs directly on hardware with tight resource and timing constraints, which is a genuinely different skill from general programming and is taught relatively rarely. This course covers microcontrollers, real-time operating systems, and peripheral interfacing through to driver development, the layers a working embedded engineer touches daily.",
"hybrid-electric-vehicle": "India's EV sector is expanding rapidly as manufacturers and startups race to build electric and hybrid vehicles, creating fresh demand for engineers who understand powertrains, battery systems, and vehicle control software. This is a genuinely new specialization inside automotive engineering, meaning fewer engineers currently have deep experience in it compared to conventional automotive roles. This course covers EV powertrains, battery management systems, and motor control, the core systems that differentiate an EV engineer from a traditional automotive engineer.",
"vlsi": "Chip design is a specialised, high-value skill sought by semiconductor and product companies building custom hardware, from processors to the embedded chips inside everyday electronics. It's a smaller, more technical field than most software roles, which means fewer engineers compete for these positions but the entry bar (digital design fundamentals, hardware description languages, and synthesis) is genuinely higher. This course builds that foundation through Verilog HDL and simulation work, the same tools used in real chip design pipelines.",
"iot": "Connected devices are expanding across manufacturing, agriculture, healthcare, and smart-city projects, all needing engineers who can build the IoT stack end to end, from a physical sensor through to a cloud dashboard. It's a cross-disciplinary role that touches embedded hardware, networking protocols, and cloud services, which is part of why companies struggle to find engineers who are comfortable across the whole stack rather than just one layer of it. This course walks through that full pipeline, sensors and connectivity through to industrial IoT and legacy system integration.",
"robotics": "Automation and robotics are growing across manufacturing, logistics, and research, creating demand for engineers who understand control systems, kinematics, and robotic platforms rather than just software in isolation. As factories and warehouses automate more of their operations, companies need engineers who can design, program, and integrate robotic systems into real production environments. This course covers the mechanical and software sides together: kinematics, control systems, ROS, and sensor integration, the combination that a working robotics engineer actually needs.",
"power-systems": "Power generation, transmission, and grid modernisation remain core to India's infrastructure, keeping demand steady for power systems engineers even as the broader energy sector shifts toward renewables and smarter grids. Utilities, EPC contractors, and infrastructure firms need engineers who understand generation, transmission and distribution, and protection systems well enough to design and maintain reliable power networks. This course builds that foundation, the same fundamentals that power sector recruiters screen for at the entry level.",
"autocad": "AutoCAD is the industry-standard drafting tool used across mechanical, civil, and architectural design offices, which makes it close to a baseline requirement for most design and drafting roles rather than an optional extra. Nearly every design office, from a small local firm to a large engineering consultancy, expects incoming engineers to already know how to produce accurate, standards-compliant drawings. This course covers 2D drafting through 3D modeling, dimensioning, and plotting, the practical skills a junior drafter or design engineer uses on day one.",
"catia": "CATIA is widely used in automotive and aerospace design offices for parametric 3D modeling, a valued specialised skill for product design roles where components need to be precisely modeled and easily modified. Because CATIA has a steeper learning curve than general CAD tools, engineers who know it well are more scarce and more sought after by the automotive and aerospace firms that standardize on it. This course covers sketching, part design, assembly design, and surface modeling, the core parametric modeling skills those industries screen for.",
"car-design": "Automotive OEMs and design studios need stylists and design engineers who understand form, aerodynamics, and surfacing well enough to turn a concept sketch into a manufacturable design. It's a genuinely competitive, design-led specialization inside automotive engineering, sitting between art and engineering, which means portfolio quality matters as much as technical modeling skill. This course covers automotive design fundamentals, aerodynamics, and surfacing through to rendering and presentation, building the kind of portfolio piece that automotive design studios actually look for.",
"construction-planning-structural-analysis": "Every construction project needs planners and analysts who can manage schedules, costs, and structural safety, a core function across contractors, infrastructure firms, and consulting engineers regardless of project size. Poor planning and structural miscalculations are two of the most expensive mistakes in construction, which is why firms specifically screen for people who understand both the scheduling and the engineering side of a project. This course covers construction planning, project scheduling, and structural analysis fundamentals together, the combination most civil engineering employers actually test for.",
"finance": "Every company needs people who understand financial statements, valuation, and modeling, which makes finance one of the most transferable commerce skill sets, useful whether you end up in a bank, a startup finance team, or corporate accounting. Financial literacy at this level is the entry requirement for a wide range of roles: financial analyst, finance executive, accounts executive, and beyond, and it's a skill set that compounds well with later specializations like investment banking or equity research. This course builds that foundation through financial statements, valuation basics, and financial modeling, taught the way it's actually used on the job.",
"digital-marketing": "Nearly every business now runs digital campaigns, creating steady demand for marketers who understand SEO, paid advertising, and analytics well enough to actually move a business metric, not just post content. As marketing budgets shift further from traditional to digital channels, companies of every size need people who can run a Google or Meta ad campaign, understand search rankings, and read the analytics that tell them what's working. This course covers that practical toolkit end to end, from strategy through to the platforms and dashboards marketers use daily.",
"hr-management": "Every organisation needs HR professionals to manage hiring, onboarding, and people operations, a stable, evergreen career path that doesn't disappear during downturns the way some specialist roles do. As companies scale, HR moves from an administrative function to a strategic one, tracking metrics, running structured hiring processes, and managing compliance, which raises the bar for what an HR hire is expected to know. This course covers the talent lifecycle, recruitment and onboarding, and HR analytics, the working knowledge behind most entry-level HR roles.",
"business-analytics": "Businesses increasingly rely on data to make decisions, creating demand for analysts who can turn numbers into recommendations rather than just build charts. The role sits at the intersection of SQL, business intelligence tooling, and communication: you need to pull the right data, visualize it clearly, and explain what it means to people making a decision. This course builds all three together, SQL fundamentals, BI dashboards, and data-driven decision frameworks, so the output is a usable business skill, not just a technical one.",
"stock-marketing": "India's retail investing boom has grown demand for people who understand markets, trading, and investment research, both for their own investing and increasingly as a professional skill inside broking firms, research desks, and wealth management. Understanding how markets actually move, not just where to click to place a trade, is what separates someone who can analyze an opportunity from someone who's just guessing. This course covers market fundamentals, technical and fundamental analysis, and trading strategy, the analytical foundation behind roles in equity research and trading.",
"sap-fico": "SAP FICO specialists are consistently hired by IT services and consulting firms implementing SAP finance modules for enterprise clients, because SAP implementations require people who understand both the software configuration and the underlying accounting processes. It's a specialized, well-compensated niche inside the broader SAP ecosystem, since financial accounting and controlling modules are core to almost every SAP rollout. This course covers financial accounting (FI), controlling (CO), and business process mapping together, the exact skill combination SAP FICO consulting roles screen for.",
"supply-chain-management": "Every manufacturing and retail business depends on efficient supply chains, keeping demand steady for planning and logistics professionals who can keep inventory, procurement, and distribution running smoothly. As Indian manufacturing and e-commerce scale up, companies increasingly need people who understand the full supply chain, not just one link in it, from procurement through to last-mile delivery. This course covers procurement, inventory and logistics, and demand planning tools together, the working knowledge behind supply chain analyst and logistics roles.",
"sales-force": "Salesforce is one of the most widely deployed CRM platforms globally, and certified administrators are in high demand at IT services firms and enterprises that run their sales and customer operations on it. Because so many companies already use Salesforce, the practical bottleneck is finding administrators who can configure objects, workflows, and automations rather than needing to build a CRM from scratch. This course covers the platform fundamentals, objects and workflows, and automation and reporting, the day-to-day skill set behind a Salesforce administrator role.",
"web3": "Blockchain and decentralised applications are an emerging area for companies exploring digital assets, smart contracts, and Web3 products, and it remains one of the newer, faster-moving specializations in tech. Because the field is young, there's less competition from experienced candidates than in mainstream software roles, but it also means the skill set changes faster and requires more self-directed learning to stay current. This course covers blockchain basics, smart contracts, decentralized applications, and digital assets, the foundation for roles in blockchain development and Web3 products.",
"investment-banking": "Investment banking and corporate finance roles require strong grounding in valuation, financial markets, and analysis, and are sought after by banks, boutique advisory firms, and corporates building out in-house finance teams. It's a competitive, analytically demanding field where the entry bar is largely about financial modeling and market literacy rather than a specific degree, which is why structured, practical training matters. This course covers financial markets, corporate finance, and valuation and investment analysis together, the technical foundation investment banking and equity research roles are built on.",
"acca-f4": "ACCA-aligned legal and corporate law knowledge is valued by accounting, audit, and compliance teams working with international standards, particularly at firms that serve multinational or globally-facing clients. Understanding business and corporate law isn't optional for accounting and audit professionals working at that level, since compliance failures are expensive and legal literacy is what prevents them. This course covers legal systems and contracts, company law, and ACCA exam-aligned practice, built specifically around the F4 syllabus for students pursuing the ACCA qualification.",
"bioinformatics": "Genomics and pharma research increasingly rely on bioinformatics to process and interpret biological data, a growing niche at research institutions and biotech companies working on genomics, drug discovery, and precision medicine. It's a cross-disciplinary field sitting between biology and computer science, which means candidates who are comfortable with both sides are relatively rare and correspondingly valuable to research teams. This course covers sequence analysis, BLAST, and bioinformatics pipelines, the practical tools used in real genomic and molecular research workflows.",
"microbiology": "Microbiology skills apply across diagnostics labs, pharma quality control, and food safety testing, three sectors that all depend on trained microbiologists to keep products and diagnoses reliable. As India's pharmaceutical and food processing industries grow, so does the need for lab-trained professionals who understand microbial techniques well enough to run quality and safety testing independently. This course covers microbial techniques, culturing and staining, and their industry applications, the practical lab skill set behind microbiologist and quality control roles.",
"molecular-biology": "Molecular biology techniques are core to diagnostics, pharma R&D, and academic and clinical research labs, wherever work happens at the level of DNA, RNA, and proteins rather than whole organisms. It's one of the more technically demanding life-science specializations, since techniques like PCR and gel electrophoresis require careful, precise lab technique that takes real practice to master. This course covers DNA/RNA techniques and PCR hands-on, the foundational skill set for research associate and lab technician roles in molecular biology.",
"medical-coding": "Healthcare providers and insurers need certified medical coders to process claims accurately, a fast-growing outsourced healthcare function in India as US and global healthcare systems increasingly offshore this work. It's a detail-oriented role that doesn't require a clinical degree but does require fluency in coding standards, which makes it an accessible entry point into the healthcare and healthcare-BPO sector. This course covers ICD coding, CPT coding, and HIPAA basics, the standards-based knowledge medical coding employers test candidates on directly.",
"nano-science-technology": "Nanotechnology research feeds into materials science, electronics, and pharma applications, mostly within research institutions and R&D teams working at the boundary of physics, chemistry, and materials engineering. It's a research-heavy specialization rather than a high-volume hiring field, which means it suits students specifically aiming at research associate or R&D trainee roles rather than mass-market employment. This course covers nanomaterials, characterization techniques, and their applications, the foundational knowledge for entry-level research roles in this space.",
"genetic-engineering": "Gene editing and biotech research roles are growing at pharma, agri-biotech, and academic research labs as CRISPR and related techniques move from research novelty to standard lab practice. It's a fast-evolving field where foundational lab technique (vectors, cloning, gene editing basics) matters more at the entry level than specialization, since most labs train further specialization on the job. This course covers gene editing fundamentals, vectors and cloning, and lab applications, the groundwork for research associate and lab technician roles in genetic engineering.",
"pharmacovigilance": "Pharma companies and CROs are legally required to monitor drug safety, creating steady, regulation-driven demand for pharmacovigilance associates that doesn't fluctuate the way many other roles do. Because this work is compliance-driven, it offers unusually stable, process-oriented career paths within the pharmaceutical and clinical research sector, especially for candidates from a life-sciences or pharmacy background. This course covers adverse-event monitoring, drug safety reporting, and regulatory basics, the practical knowledge pharmacovigilance associate roles are built on.",
"food-science-technology": "Food manufacturers and quality teams need trained professionals in processing, safety, and quality systems as India's packaged food and FMCG industry continues to grow and formalize. Every food product that reaches a shelf has passed through quality and safety checks run by food technologists, making this a consistently needed function rather than a cyclical one. This course covers food chemistry, processing, and food safety systems together, the working knowledge behind food technologist and quality assurance roles.",
"nutrition-health-management": "Growing health awareness has increased demand for trained professionals in nutrition counselling, wellness programs, and diet planning, both within healthcare settings and the broader wellness and fitness industry. As more companies build wellness programs for employees and more consumers seek personalized nutrition guidance, the demand for people with structured nutrition science training keeps expanding beyond just clinical settings. This course covers applied nutrition science and health management fundamentals, building a foundation for nutrition associate and wellness coordinator roles.",
"sensory-science": "FMCG and food companies rely on trained sensory panels and analysts to evaluate product quality and consumer acceptance before a product ever reaches a shelf. It's a specialized, less commonly taught skill inside food science that combines scientific method with structured taste, smell, and texture evaluation, making trained sensory analysts genuinely useful to R&D and quality teams. This course covers sensory evaluation methods and quality assessment for food and consumer products, the practical foundation for sensory analyst and R&D associate roles.",
}

with open(PATH, encoding="utf-8") as f:
    content = f.read()

count = 0
for slug, long_scope in SCOPE_LONG.items():
    pattern = re.compile(
        r'(slug: "' + re.escape(slug) + r'".*?\n\s*scope: )"[^"]*"',
        re.DOTALL
    )
    new_content, n = pattern.subn(lambda m: m.group(1) + __import__("json").dumps(long_scope, ensure_ascii=False), content, count=1)
    if n == 0:
        print("NOT FOUND:", slug)
    else:
        content = new_content
        count += n

with open(PATH, "w", encoding="utf-8") as f:
    f.write(content)

print("Patched", count, "of", len(SCOPE_LONG), "scope fields")
